version: "3"
services: 
    app_builder: 
      build:
        context: .
        dockerfile: ./linux.Dockerfile
      image: app_builder
      container_name: app_builder
      hostname: app_builder
      volumes: 
        - ./:/project